markdown: kramdown
permalink: /:title/
relative_permalinks: false
sass:
  sass_dir: assets/stylesheets
defaults:
  category: 'news'
gems:
  - jekyll-paginate
  - jekyll-redirect-from
paginate: 5
paginate_path: /blog/page/:num
